# frontend/Dockerfile

#######################
# Etapa 1: Build      #
#######################
FROM node:20-alpine AS builder

WORKDIR /app

# Copiar dependencias
COPY package*.json ./

RUN npm install

# Copiar resto del código
COPY . .

# Construir versión de producción
RUN npm run build

#######################
# Etapa 2: Servir     #
#######################
FROM nginx:alpine

# Copiar build al directorio público de Nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# (Opcional) Copiar config personalizada de nginx si la usas
# COPY nginx.conf /etc/nginx/nginx.conf

# Puerto donde escucha Nginx
EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
