// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvubdrtscegepiptqvdp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2dWJkcnRzY2VnZXBpcHRxdmRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwMTE2MjEsImV4cCI6MjA3NzU4NzYyMX0.hvPliGwY34COTvmhH3H_aVdxkdYIulQSje_vs41a6t8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
