"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.server = void 0;
var express_1 = require("express");
var cors_1 = require("cors");
var dotenv_1 = require("dotenv");
var main_routes_js_1 = require("./routes/main.routes.js");
var errorHandler_js_1 = require("./middleware/errorHandler.js");
dotenv_1.default.config();
var app = (0, express_1.default)();
var port = process.env.PORT || 3000;
app.use((0, cors_1.default)());
app.use(express_1.default.json());
app.use('/api', main_routes_js_1.default);
app.use(errorHandler_js_1.errorHandler);
var server = app.listen(port, function () {
    console.log("\uD83D\uDE80 Servidor corriendo en http://localhost:".concat(port));
});
exports.server = server;
exports.default = app;
