"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var products_controller_js_1 = require("@controllers/products.controller.js");
var auth_js_1 = require("@middleware/auth.js");
var product_schema_js_1 = require("@validations/product.schema.js");
var router = (0, express_1.Router)();
var productController = new products_controller_js_1.ProductController();
router.get('/', productController.getAllProducts);
router.get('/:id', productController.getProductById);
router.post('/', auth_js_1.auth, product_schema_js_1.createProductValidation, productController.createProduct);
router.put('/:id', auth_js_1.auth, product_schema_js_1.updateProductValidation, productController.updateProduct);
router.delete('/:id', auth_js_1.auth, productController.deleteProduct);
exports.default = router;
